import Head from "next/head";
import { Inter } from "next/font/google";
import prisma from "../../lib/prisma";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import { Table, Thead, Tbody, Button, ButtonGroup, Tr, Th, Td, TableCaption, TableContainer } from "@chakra-ui/react";
// import Image from "next/image";
// import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ books }) {
  const router = useRouter();
  const [bookData, setBookData] = useState(books);

  const handleDetail = (id) => {
    router.push(`/detail/${id}`);
  };

  useEffect(() => {}, [bookData]);

  const fetchBooks = () => {
    fetch("/api/books")
      .then((res) => {
        return res.json();
      })
      .then((data) => {
        setBookData(data);
      })
      .catch((err) => {
        console.log(err);
      });
  };

  const handleDelete = (id) => {
    fetch(`/api/books/${id}`, {
      method: "DELETE",
    })
      .then((res) => {
        return res.json();
      })
      .then((data) => {
        console.log(data);
        fetchBooks();
      })
      .catch((err) => {
        console.log(err);
      });
  };

  const handleEdit = (id) => {
    router.push(`/edit/${id}`);
  };

  return (
    <>
      <Head>
        <title>Books App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* {JSON.stringify(books)} */}
        <TableContainer>
          <Table variant="simple">
            <TableCaption>List books app</TableCaption>
            <Thead>
              <Tr>
                <Th>Id</Th>
                <Th>Title</Th>
                <Th>Author</Th>
                <Th>Publisher</Th>
                <Th>Year</Th>
                <Th>Pages</Th>
                <Th>Image</Th>
              </Tr>
            </Thead>
            <Tbody>
              {bookData.map((book, index) => {
                return (
                  <Tr key={index}>
                    <Td>{book.id}</Td>
                    <Td>{book.title}</Td>
                    <Td>{book.author}</Td>
                    <Td>{book.publisher}</Td>
                    <Td>{book.year}</Td>
                    <Td>{book.pages}</Td>
                    <Td>{book.image}</Td>
                    <Td>
                      <ButtonGroup spacing="2">
                        <Button colorScheme="blue" onClick={(e) => handleDetail(book.id)}>
                          Detail
                        </Button>
                        <Button colorScheme="yellow" onClick={(e) => handleEdit(book.id)}>
                          Edit
                        </Button>
                        <Button colorScheme="red" onClick={(e) => handleDelete(book.id)}>
                          Delete
                        </Button>
                      </ButtonGroup>
                    </Td>
                  </Tr>
                );
              })}
            </Tbody>
          </Table>
        </TableContainer>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  let books = await prisma.Book.findMany();

  books = JSON.parse(JSON.stringify(books));
  return {
    props: {
      books,
    },
  };
};
